language: node_js
os:
  - linux
cache:
  yarn: true
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - node
stages:
  - name: lint
  - test
  - name: deploy

jobs:
  include:
    - stage: lint
      script:
        - yarn lint:types
        - yarn lint
    - stage: test
      script:
        - yarn test
    - stage: deploy
      script:
        - yarn build
      deploy:
        provider: script
        email: '$npm_email'
        api_key: '$npm_key'
        skip_cleanup: true
        script:
          - yarn release
        on:
          tags: false

branches:
  only:
    - master
